sudo: required
dist: trusty

services:
  - docker

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce

script:
  - docker-compose -f src/DartLeague/docker-compose.ci.build.yml up
  - docker-compose build -f docker-compose.yml -f docker-compose.override.yml -f docker-compose.vs.release.yml -p dartleagueweb-release --no-cache dartleagueweb

after_success:
  - docker ps
  - docker tag dartleagueweb dartleagueweb:$VERSION_PREFIX$TRAVIS_BUILD_NUMBER
  - docker images
  - if [ "$TRAVIS_BRANCH" == "develop" ]; then
      docker tag dartleagueweb registry.thecitizens.net/dartleagueweb
      docker tag registry.thecitizens.net/dartleagueweb "registry.thecitizens.net/dartleagueweb:$VERSION_PREFIX$TRAVIS_BUILD_NUMBER"
      docker push registry.thecitizens.net/dartleagueweb
    fi
