sudo: required
dist: trusty

services:
  - docker

before_install:
  - docker version
  - docker-compose version

script:
  - docker-compose -f src/DartLeague/DartLeague.Web/docker-compose.ci.build.yml up


