version: '2.1'

services:
  nginx:
    image: nginx
    restart: always
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/etc/nginx/conf.d"
      - "/etc/nginx/vhost.d"
      - "/usr/share/nginx/html"
      - "${SSL_CERT_PATH}:/etc/nginx/certs:ro"
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"

  nginx-gen:
    image: jwilder/docker-gen
    container_name: nginx-gen
    restart: always
    volumes_from:
      - "nginx"
    volumes:
      - "/etc/docker/nginx/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro"
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.docker_gen"
    command: "-notify-sighup nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf"
    links:
      - nginx

  nginx-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    container_name: nginx-letsencrypt
    volumes_from:
      - "nginx"
    volumes:
      - "${SSL_CERT_PATH}:/etc/nginx/certs:rw"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    links:
      - nginx

  dartleagueweb:
    image: registry.thecitizens.net/dartleagueweb:${DARTLEAGUE_VERSION}
    restart: always
    container_name: dartleagueweb
    volumes:
      - "${FILE_STORAGE_PATH}:/storage"
    environment:
      - "VIRTUAL_HOST=${DARTLEAGUE_HOST_NAME}"
      - "LETSENCRYPT_HOST=${LETSENCRYPT_HOST}"
      - "LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}"
    links:
      - "mysqlserver"

  mysqlserver:
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - "${MYSQL_DATA_PATH}:/var/lib/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
