version: '2.1'

services:
  dartleagueweb:
    image: dartleagueweb
    build:
      context: ./DartLeague.Web
      dockerfile: Dockerfile
    environment:
      - "BrowsableFile:Storage=/storage"
    volumes:
      - "C:/DevData/DartLeague/storage:/storage"
    links:
    - mysqlserver
  mysqlserver:
    image: mysql
    ports:
    - "3306:3306"
    volumes:
    - "C:/DevData/DartLeague/mysql:/var/lib/mysql"
    environment:
    - MYSQL_ROOT_PASSWORD=my-secret-pw