version: '3.4'

services:
  ci-build:
    image: mcr.microsoft.com/dotnet/core/sdk:3.0
    volumes:
      - .:/src
    working_dir: /src
    command: /bin/bash -c "dotnet restore ./DartLeague.sln && dotnet publish ./DartLeague.sln -c Release -o ./obj/Docker/publish"
