version: '3.4'

services:
  dartleaguedbsolo:
    image:  mcr.microsoft.com/mssql/server
    ports:
    - "9888:1433"
    volumes:
    - dartleaguesolosqlvolume:/var/opt/mssql
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: AStrong!Passw0rd
      MSSQL_PID: Express
volumes:
  dartleaguesolosqlvolume: