version: '3'

services:
  dartleagueweb:
    image: dartleagueweb
    build:
      context: ./DartLeague.Web
      dockerfile: Dockerfile
    environment:
      - "BrowsableFile:Storage=/storage"
    volumes:
      - "C:/DevData/DartLeague/storage:/storage"
    links:
    - dartleaguedb
  dartleaguedb:
    image: store/microsoft/mssql-server-linux:2017-latest
    ports:
    - "1433:1433"
    volumes:
    - dartleaguesqlvolume:/var/opt/mssql
    environment:
    - ACCEPT_EULA=Y
    - SA_PASSWORD=AStrong!Passw0rd
    - MSSQL_PID=Express
volumes:
  dartleaguesqlvolume: